# Generated by Django 4.1.7 on 2023-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='upload/')),
                ('image_url', models.CharField(blank=True, default='', max_length=200)),
                ('patient_name', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
