# Generated by Django 4.1.7 on 2023-02-18 15:52

import ARViewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARViewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idmodel',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='idmodel',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=ARViewer.models.p_and_r),
        ),
    ]
